#!/bin/bash

PROJECT_HOME=$(dirname "$0")/..

deno run --allow-read --allow-write --allow-net --unsafely-ignore-certificate-errors \
    "https://raw.githubusercontent.com/littlelanguages/parspiler-cli/main/mod.ts" kotlin \
    --verbose \
    --directory="$PROJECT_HOME"/src/main/kotlin \
    --package=com.ucle.parser \
    "$PROJECT_HOME"/docs/mini/Grammar.lllg
